import type { Tur } from "./tipler";

export const endpointYonetimiTuru: Tur = {
  kimlik: "endpoint-yonetimi",
  baslik: "Endpoint yönetimi",
  aciklama: "Satırda ne var, devre durumları, olay filtresi ve hız sınırı.",
  adimlar: [
    {
      kimlik: "endpoint-yonetimi.satir",
      rota: "/endpointler",
      anchor: "endpoint-satir",
      yerlesim: "bottom",
      baslik: "Satırda ne var",
      metin:
        "URL, olay filtresi, retry profili, 24 saatlik başarı oranı, sağlık skoru ve devre durumu.",
      onkosul: (b) => b.endpointSayisi > 0,
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
    {
      kimlik: "endpoint-yonetimi.devre-rozeti",
      rota: "/endpointler",
      anchor: "endpoint-devre-rozeti",
      yerlesim: "left",
      baslik: "Üç devre durumu",
      metin: "Sağlıklı: normal. Yarı açık: sistem yoklama yapıyor. Açık: teslimat durdu.",
      onkosul: (b) => b.endpointSayisi > 0,
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
    {
      kimlik: "endpoint-yonetimi.devre-sifirla",
      rota: "/endpointler",
      anchor: "endpoint-devre-sifirla",
      yerlesim: "left",
      baslik: "Devreyi elle kapatın",
      metin: "Alıcı tarafındaki sorunu çözdüyseniz beklemeden buradan sıfırlayın.",
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
    {
      kimlik: "endpoint-yonetimi.form-filtre",
      rota: "/endpointler",
      anchor: "endpoint-form-filtre",
      yerlesim: "right",
      baslik: "Olay filtresi",
      metin: "Yalnız gerekli olay tiplerine abone olun. Her şeye abone olmak cazip ama gürültü üretir.",
      ilerleme: "ileri-butonu",
      etkilesim: "serbest",
    },
    {
      kimlik: "endpoint-yonetimi.secret-rotasyon",
      rota: "/endpointler",
      anchor: "endpoint-secret-rotasyon",
      yerlesim: "left",
      baslik: "Secret rotasyonu",
      metin: "Yeni secret üretir; eski secret 24 saat daha doğrulamada geçerli kalır. Kesintisiz geçiş bu sayede.",
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
    {
      kimlik: "endpoint-yonetimi.secret-goster",
      rota: "/endpointler",
      anchor: "endpoint-secret-goster",
      yerlesim: "bottom",
      baslik: "Bir kez gösterilir",
      metin: "Secret yalnız üretim anında görünür. Kopyalamadan pencereyi kapatmayın.",
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
  ],
};
