import type { Tur } from "./tipler";

export const tanitimTuru: Tur = {
  kimlik: "tanitim",
  baslik: "Platformu tanıyın",
  aciklama: "Panelin tamamında 2 dakikalık bir gezinti — kota, endpoint, teslimat ve audit.",
  adimlar: [
    {
      kimlik: "tanitim.ozet",
      rota: "/",
      anchor: "anasayfa-istatistikler",
      yerlesim: "bottom",
      baslik: "Günün özeti",
      metin:
        "Kota, endpoint sayısı, açık devre ve sağlık uyarıları tek bakışta. Her sabah ilk bakacağınız yer.",
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
    {
      kimlik: "tanitim.devre",
      rota: "/",
      anchor: "anasayfa-devre-karti",
      yerlesim: "bottom",
      baslik: "Açık devre nedir?",
      metin:
        "Bir endpoint üst üste başarısız olursa devresi açılır ve teslimat denemeleri durur. Buradaki sayı 0'dan büyükse bir aboneniz sorun yaşıyor.",
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
    {
      kimlik: "tanitim.olaylara-git",
      rota: "/",
      anchor: "nav-/olaylar",
      yerlesim: "bottom",
      baslik: "Olaylar",
      metin: "Sisteme giren her event burada. Gidelim.",
      ilerleme: { tip: "anchor-tikla" },
      etkilesim: "sadece-anchor",
    },
    {
      kimlik: "tanitim.filtre",
      rota: "/olaylar",
      anchor: "olaylar-filtre",
      yerlesim: "bottom",
      baslik: "Filtre",
      metin: "Bir olay tipi yazın (örn. siparis.olusturuldu) — liste anında daralır.",
      ilerleme: "ileri-butonu",
      etkilesim: "serbest",
    },
    {
      kimlik: "tanitim.teslimat-ozeti",
      rota: "/olaylar",
      anchor: "olaylar-teslimat-ozeti",
      yerlesim: "left",
      baslik: "n/m başarılı",
      metin:
        "Her olay, filtresine uyan her endpoint için ayrı bir teslimat üretir. Bu oran kaçının ulaştığını söyler.",
      onkosul: (b) => b.olaySayisi > 0,
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
    {
      kimlik: "tanitim.endpoint-ekle",
      rota: "/endpointler",
      anchor: "endpoint-yeni-buton",
      yerlesim: "bottom",
      baslik: "Endpoint ekleyin",
      metin: "Bir URL, bir olay filtresi, bir retry profili. Butona tıklayın.",
      ilerleme: { tip: "anchor-tikla" },
      etkilesim: "sadece-anchor",
    },
    {
      kimlik: "tanitim.retry-profili",
      rota: "/endpointler",
      anchor: "endpoint-form-retry-profili",
      yerlesim: "right",
      baslik: "Retry profili",
      metin:
        "HIZLI kısa aralıklarla az dener, UZUN saatlere yayılır. Alıcının doğasına göre seçin.",
      ilerleme: "ileri-butonu",
      etkilesim: "serbest",
    },
    {
      kimlik: "tanitim.saglik-skoru",
      rota: "/endpointler",
      anchor: "endpoint-saglik-skoru",
      yerlesim: "left",
      baslik: "Sağlık skoru",
      metin:
        "Son 24 saatin başarı oranı ve gecikmesinden hesaplanır. 70'in altına düşerse audit'e uyarı yazılır. Hiç trafik yoksa \"—\" görürsünüz; bu \"kötü\" değil \"bilinmiyor\" demektir.",
      onkosul: (b) => b.endpointSayisi > 0,
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
    {
      kimlik: "tanitim.test-gonder",
      rota: "/test",
      anchor: "test-gonder-buton",
      yerlesim: "top",
      baslik: "Şimdi deneyelim",
      metin:
        "Terminale dokunmadan gerçek bir olay gönderin — teslimatın sonucuna yönlendirileceksiniz.",
      ilerleme: { tip: "anchor-tikla" },
      etkilesim: "sadece-anchor",
    },
    {
      kimlik: "tanitim.timeline",
      rota: null,
      anchor: "teslimat-timeline",
      yerlesim: "left",
      baslik: "İşte olan biten",
      metin:
        "Her deneme burada: zaman, HTTP kodu, süre ve sonraki denemeye kalan backoff. Ürünün asıl değeri bu ekranda.",
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
    {
      kimlik: "tanitim.kota",
      rota: "/kullanim",
      anchor: "kullanim-kota-cubugu",
      yerlesim: "bottom",
      baslik: "Kota",
      metin:
        "Aylık teslimat hakkınız. Dolarsa yeni olay girişleri 429 ile reddedilir — sürpriz olmasın diye burada.",
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
    {
      kimlik: "tanitim.audit",
      rota: "/audit",
      anchor: "audit-baslik",
      yerlesim: "bottom",
      baslik: "Denetim izi",
      metin:
        "Devre sıfırlama, secret rotasyonu, API anahtarı üretimi — hassas her aksiyon burada kalıcı iz bırakır. Tur bitti, iyi çalışmalar.",
      ilerleme: "ileri-butonu",
      etkilesim: "engelli",
    },
  ],
};
